### ISSUE TITLE
Allow for alternate opt-in

### ISSUE THREAD

**Issue by chrisronline** [chrisronline/angular-float-labels#3]
Per [this fork](https://github.com/adammahmood/angular-float-labels), this plugin should allow consumers to choose if they want to use `placeholder` or something more custom.

@adammahmood

**Comment by adammahmood** [comment]
Just released another version on my fork: https://github.com/adammahmood/angular-float-labels

Now supports use of directive via class name or attribute and defaults to use placeholder text if floatlabel text not provided.   

Thanks for the initial code. Worked like a charm, but wasn't suitable to takeover every input with floating labels and always use the placeholder text.

**Comment by chrisronline** [comment]
Thanks @adammahmood - I'll get to this when I can (hopefully this week)

**Comment by chrisronline** [comment]
What if we exposed two separate directives through separate files that use either `placeholder` or `floatlabel`? Then, the consumer could choose which implementation works better for them. We'd leave `placeholder` the default to support existing consumers

**Comment by chrisronline** [comment]
Two versions available in v0.1.0
